version: 0.2

phases:

  pre_build:
      commands: 
        
  build:
      commands:
          - echo "//npm.pkg.github.com/:_authToken=\${GIT_TOKEN}" >> .npmrc
          - make install CI=true
          - make build-prod
          - make build-single-spa
          - make test-cov
          
  post_build:
      commands:        
        - find . ! -regex '^./build\(/.*\)?' -delete        
        - mv ./build/* .
        - mv ./dist/* .        
        - rm -rf ./build
        - rm -rf ./dist
artifacts:
  files:
    - '**/*'
