AWSTemplateFormatVersion: '2010-09-09'
Description: 'Code pipeline to build the web-app-kit application'

Parameters:
  
  Environment:
    Type: String
    Description: The environment that the pipeline is deployed to
    Default: sbx
    AllowedValues:
      - prd
      - tst
      - dev
      - stg
      - sbx
    
  StackPrefix:
    Type: String
    Description: The unique prefix following the environment name that the pipleine is deployed to
  
  StackName:
    Type: String
    Description: combination of [Environment]-[StackPrefix]-application-codepipeline

  GitHubOwner:
    Type: String
    Description: The owner of the GitHub repository
    
  GitHubRepo:
    Type: String
    Description: The GitHub repository.
    
  GitHubBranch:
    Type: String
    Description: The github branch
    Default: master

  GitToken:
    Type: AWS::SSM::Parameter::Value<String>
    Description: GitHub OAuth Token
    Default: gittoken

Resources:
  GitWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: !Sub ${StackName}-webhook
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitToken
      TargetPipeline: !Ref CodePipeline
      TargetPipelineVersion: 1
      TargetAction: web-app-kit-development
      Filters:
        - JsonPath: '$.ref'
          MatchEquals: !Sub refs/heads/${GitHubBranch}
      RegisterWithThirdParty: true
  
  ArtifactsStore:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
      BucketName: !Sub ${StackName}
  
  # Websiteaccessbucketpolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref ArtifactsStore
  #     PolicyDocument: 
  #       Version: 2012-10-17
  #       Statement:
  #         -
  #           Sid: PublicReadGetObject
  #           Effect: Allow
  #           Principal: "*"
  #           Action:
  #             - s3:GetObject
  #           Resource: 
  #             !Join
  #               - ''
  #               - - !GetAtt ArtifactsStore.Arn
  #                 - "/*"              
    
  CodePipelineRole:
    Type: AWS::IAM::Role
    DependsOn: ArtifactsStore
    Properties:
      RoleName: !Sub ${StackName}-code-pipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codepipeline.amazonaws.com'
            - 'cloudformation.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: Permissions
        PolicyDocument:
          Version: '2012-10-17'      
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            - s3:PutObject
            Resource: 
              !Join
                - ''
                - - !GetAtt ArtifactsStore.Arn
                  - "/*"
          - Effect: Allow
            Action:
            - "*"
            Resource: "*"
  
  CodeBuildRole:
    Type: AWS::IAM::Role
    DependsOn: ArtifactsStore
    Properties:
      RoleName: !Sub ${StackName}-code-build-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['sts:AssumeRole']
          Principal:
            Service: ['codebuild.amazonaws.com']
      Path: /
      Policies:
      - PolicyName: Permissions
        PolicyDocument:
          Version: '2012-10-17'       
          Statement:
            - Sid: "CloudWatchLogPermissions"
              Effect: "Allow"
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource:              
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${StackName}-buildproject:*              
            - Sid: "ArtifactStorePermissions"
              Effect: "Allow"
              Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              Resource:
                !Join
                  - ''
                  - - !GetAtt ArtifactsStore.Arn
                    - "/*"
            - Sid: "DescribeStacks"
              Effect: "Allow"
              Action: cloudformation:DescribeStacks
              Resource: "*"

  BuildApplicationStack:
    Type: AWS::CodeBuild::Project
    DependsOn: ArtifactsStore
    Properties:
      Name:  !Sub ${StackName}-buildproject
      Description: Builds the resources required for the organisation service stack
      TimeoutInMinutes: 15
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.14.1-1.7.0
        EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: !Ref Environment
        - Name: STACK_PREFIX
          Value: !Ref StackPrefix
        - Name: GIT_TOKEN
          Value: !Ref GitToken
      Source:
        BuildSpec: infrastructure/application/buildspec.yml
        Type: CODEPIPELINE

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${StackName}
      ArtifactStore:
        Location: !Ref ArtifactsStore
        Type: S3
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
      - Name: Source
        Actions:
        - Name: web-app-kit-development
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
            - Name: SourceArtifact
          Configuration:
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo
            PollForSourceChanges: 'false'
            Branch: !Ref GitHubBranch
            OAuthToken: !Ref GitToken
          RunOrder: 1
      - Name: Build
        Actions:        
        - Name: build-web-app-kit-application
          RunOrder: 1
          InputArtifacts:
            - Name: SourceArtifact
          OutputArtifacts:
            - Name: ApplicationFrameStackResources
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          Configuration:
            ProjectName: !Ref BuildApplicationStack

      - Name: Deploy
        Actions:
        - Name: deploy-web-app-kit-application
          RunOrder: 2
          InputArtifacts:
            - Name: ApplicationFrameStackResources
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: S3
          Configuration:
            BucketName: !Ref ArtifactsStore
            Extract: true